apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: static-test
  labels:
    app: static-test-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/voidstar17/static_test
    contextDir: /
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: static-test:latest
