apiVersion: apps/v1
kind: Deployment
metadata:
  name: static_test_deployment
spec:
  selector:
    matchLabels:
      app: static_test
  replicas: 1
  template:
    metadata:
      labels:
        app: static_test
    spec:
      containers:
      - name: static_test_app
        image: https://github.com/voidstar17/static_test/blob/main/Dockerfile:0.0.1
        ports:
        - containerPort: 80
