apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun
  namespace: void17-dev
spec:
  selector:
    matchLabels:
      app: bun
  replicas: 2
  template:
    metadata:
      labels:
        app: bun
    spec:
      containers:
        - name: bun
          image: int049/httpd_bun:2
          ports:
            - containerPort: 8080
          readinessProbe:
           httpGet:
            scheme: HTTPS
            path: /index.html
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 5
          env:
            - name: bunvar
              value: hellobun
            - name: bunkey
              valueFrom:
                    configMapKeyRef:
                        name: cm-bun 
                        key: bun.property.1
                        optional: true
            - name: bunuser
              valueFrom:
               secretKeyRef:
                 key: username
                 name: bun-secret
